// Converts the app mark (apps/desktop/src/renderer/src/assets/mark.png) into half-block
// terminal art: each cell shows two vertical pixels with ▀/▄, foreground = top, background = bottom.
// Run once after the mark changes: `pnpm --filter xari-bulbul-cli orchid`. Output is committed.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PNG } from 'pngjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const src = path.resolve(here, '../../desktop/src/renderer/src/assets/mark.png')
const out = path.resolve(here, '../src/theme/orchid.generated.ts')
const png = PNG.sync.read(fs.readFileSync(src))

/** Area-average a box of source pixels (alpha-weighted) → [r, g, b, a]. */
function sample(x0, y0, x1, y1) {
  let r = 0, g = 0, b = 0, a = 0, n = 0
  for (let y = Math.floor(y0); y < Math.ceil(y1); y++) {
    for (let x = Math.floor(x0); x < Math.ceil(x1); x++) {
      if (x < 0 || y < 0 || x >= png.width || y >= png.height) continue
      const i = (y * png.width + x) * 4
      const al = png.data[i + 3] / 255
      r += png.data[i] * al
      g += png.data[i + 1] * al
      b += png.data[i + 2] * al
      a += al
      n++
    }
  }
  if (!a) return [0, 0, 0, 0]
  return [r / a, g / a, b / a, a / n]
}

const hex = ([r, g, b]) => '#' + [r, g, b].map((v) => Math.round(Math.min(255, v)).toString(16).padStart(2, '0')).join('')

function render(cols) {
  const scale = png.width / cols
  const pxRows = Math.ceil(png.height / scale)
  const rows = []
  for (let cy = 0; cy < Math.ceil(pxRows / 2); cy++) {
    const row = []
    for (let cx = 0; cx < cols; cx++) {
      const top = sample(cx * scale, cy * 2 * scale, (cx + 1) * scale, (cy * 2 + 1) * scale)
      const bot = sample(cx * scale, (cy * 2 + 1) * scale, (cx + 1) * scale, (cy * 2 + 2) * scale)
      const t = top[3] >= 0.45 ? hex(top) : null
      const b = bot[3] >= 0.45 ? hex(bot) : null
      if (t && b) row.push(['▀', t, b])
      else if (t) row.push(['▀', t, null])
      else if (b) row.push(['▄', b, null])
      else row.push([' ', null, null])
    }
    rows.push(row)
  }
  // Trim empty rows top and bottom.
  const empty = (r) => r.every((c) => c[0] === ' ')
  while (rows.length && empty(rows[0])) rows.shift()
  while (rows.length && empty(rows.at(-1))) rows.pop()
  return rows
}

const sizes = { small: render(20), large: render(30) }
const body = `// Generated by scripts/make-orchid.mjs from the app mark. Do not edit by hand.
// Each cell is [glyph, foreground, background]; null means the terminal's own colour.
export type OrchidCell = [string, string | null, string | null]
export const ORCHID: Record<'small' | 'large', OrchidCell[][]> = ${JSON.stringify(sizes)}
`
fs.writeFileSync(out, body)
for (const [k, rows] of Object.entries(sizes)) console.log(k, `${rows[0].length}×${rows.length}`)
